builds:
  - id: gypsum
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
      - goarm: windows
        goarch: arm
      - goarm: windows
        goarch: arm64
    flags:
      - -tags=jsoniter
      - -trimpath
archives:
  - replacements:
      darwin: mac
      386: x86
      amd64: x86_64
    format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - NOFILE*
changelog:
  skip: false
checksum:
  disable: true
release:
  draft: true
  prerelease: auto
dockers:
  - goos: linux
    goarch: amd64
    ids:
      - gypsum
    dockerfile: scripts/add.Dockerfile
    image_templates:
      - "ghcr.io/yuudi/gypsum:latest"
      - "ghcr.io/yuudi/gypsum:{{ .Version }}"
      - "ghcr.io/yuudi/gypsum:{{ .Major }}"
