builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
      - goarm: windows
        goarch: arm
      - goarm: windows
        goarch: arm64
    ldflags:
      - "-s -w -X gypsum.version={{.Version}} -X gypsum.commit={{.ShortCommit}}"
archives:
  - replacements:
      darwin: macOS
      386: x86
      amd64: x86_64
    format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - NOFILE*
checksum:
  disable: true
