builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
archives:
  - replacements:
      amd64: x86_64
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - public/*
checksum:
  disable: true
