name: ci

on:
  push: {}
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  workflow_dispatch: {}

jobs:
  ci:
    name: Build Go Binaries
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          stable: false
          go-version: 1.16.0-rc1

      - name: Checkout the Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache Go Modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('./go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Release Condition
        id: release_condition
        shell: bash
        run: |
          if [ ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }} == true ]
          then
            flags=""
          else
            flags="--skip-publish"
          fi
          echo "::set-output name=releaser_flags::${flags} "

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist ${{ steps.release_condition.outputs.releaser_flags }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload assets
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v2
        with:
          name: builds
          path: |
            dist/*.tar.gz
            dist/*.zip
