name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Build Go Binaries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Get frontend ref hash
        id: frontend-ref
        run: echo "::set-output name=commit::$(git submodule status | cut -f 2 -d ' ')"

      - name: Cache frontend builds
        id: cache-frontend-builds
        uses: actions/cache@v2
        with:
          path: gypsum/web
          key: gypsum-web-builds-${{ steps.frontend-ref.outputs.commit }}

      - name: Setup Nodejs
        if: steps.cache-frontend-builds.outputs.cache-hit != 'true'
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Get yarn cache directory path
        if: steps.cache-frontend-builds.outputs.cache-hit != 'true'
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn
        uses: actions/cache@v2
        if: steps.cache-frontend-builds.outputs.cache-hit != 'true'
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build frontend
        if: steps.cache-frontend-builds.outputs.cache-hit != 'true'
        run: |
          cd frontend
          yarn install
          yarn build --dest ../gypsum/web
          gzip -rk9 ../gypsum/web

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          stable: false
          go-version: 1.16.0-rc1

      - name: Cache Go Modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('./go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
